openapi: "3.0.0"
info:
  version: 1.0.0
  title: HomeNet
  description: |
    listings of properties for sale
  license:
    name: MIT
servers:
- url: http://localhost:3000
paths:
  /listings:
    get:
      summary: Lists all listings
      parameters:
        - name: "city"
          in: "query"
          required: false
          description: "Returns only listings in **city**."
          schema:
            type: string
        - name: "type"
          in: "query"
          required: false
          description: "Returns only listings of **type**."
          schema:
            type: string
        - name: "max_price"
          in: "query"
          required: false
          description: "Returns only listings with maximum price below and including **max_price**."
          schema:
            type: number
      tags:
        - listings
      responses:
        '200':
          description: Array of listings
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ResponseListings"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /listing:
    post:
      summary: Create a new listing
      tags:
        - "listing"
      responses:
        '201':
          description: Listing was created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseListing'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /listing/{id}:
    get:
      summary: List one listing
      tags:
        - "listing"
      parameters:
        - name: "id"
          in: "path"
          required: true
          description: "The listing's unique ID"
          schema:
            type: string
      responses:
        '200':
          description: One listing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseListing'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Update one listing
      tags:
        - "listing"
      parameters:
        - name: "id"
          in: "path"
          required: true
          description: "The listing's unique ID"
          schema:
            type: string
      responses:
        '200':
          description: Listing updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseListing'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete one listing
      tags:
        - "listing"
      parameters:
        - name: "id"
          in: "path"
          required: true
          description: "The listing's unique ID"
          schema:
            type: string
      responses:
        '200':
          description: Listing deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseListing'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Listing:
      type: object
      properties:
        coordinates:
          type: object
          properties:
            lng: 
              type: number
              format: float
            lat: 
              type: number
              format: float
        street:
          type: string
        location: 
          type: object
          properties:
            municipality:
              type: string
            city: 
              type: string
        type:
          type: string
        price:
          type: number
          format: uint32
        monthly_fee:
          type: number
          format: uint32
        active: 
          type: boolean
    ResponseListing:
      allOf:
      - $ref: "#/components/schemas/Listing"
      - properties:
          __v:
            type: integer
            format: uint32
          _id:
            type: string
            format: uuid
    ResponseListings:
      type: array
      items:
        $ref: "#/components/schemas/ResponseListing"
    Error:
      required:
        - error
      properties:
        error:
          type: object
          properties:
            expose:
              type: boolean
            statusCode:
              type: integer
              format: uint32
            status:
              type: integer
              format: uint32
            body:
              title: body as escaped json
              type: string
            type:
              title: fault desciption
              type: string
